
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - "DB:/var/lib/mysql"
    networks:
      - default

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - default

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - default

volumes:
  WP_files:
    driver: local
    driver_opts:
      type : none
      o: bind
      device: "/home/bsuc/data/wp_files"
  DB:
    driver: local
    driver_opts:
      type : none
      o: bind
      device: "/home/bsuc/data/db"

networks:
  default:
    driver: bridge
