
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    expose:
     - "3306"
    env_file: .env
    secrets:
      - my_db_user
      - my_db_passwd
      - my_db_root_passwd
    volumes:
      - "DB:/var/lib/mysql"
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    secrets:
      - my_db_user
      - my_db_passwd
      - my_wp_admin
      - my_wp_admin_passwd
      - my_wp_admin_email
      - my_wp_user
      - my_wp_passwd
      - my_wp_email
    env_file: .env
    volumes:
      - "WP_files:/var/www/wordpress"
    networks:
      - inception

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - static
      - wordpress
      - adminer
      - monitorix
    volumes:
      - "WP_files:/var/www/wordpress"
    networks:
      - inception

  static:
    build: ./requirements/bonus/static/
    container_name: static
    restart: always
    expose:
      - "443"
    volumes:
      - "static_files:/var/www/static"
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    expose:
      - "6379"
    depends_on:
      - wordpress
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    depends_on:
      - nginx
    volumes:
      - "WP_files:/srv/ftp"
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    expose:
      - "9000"
    networks:
      - inception

  monitorix:
    build: ./requirements/bonus/monitorix
    container_name: monitorix
    restart: always
    expose:
      - "8080"
    networks:
      - inception
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW

volumes:
  WP_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/bsuc/data/wp_files"
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/bsuc/data/db"
  static_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/bsuc/data/static_files"


networks:
  inception:
    driver: bridge

secrets:
  my_db_user:
    file: ../secrets/db_user.txt
  my_db_passwd:
    file: ../secrets/db_password.txt
  my_db_root_passwd:
    file: ../secrets/db_root_password.txt
  my_wp_admin:
    file: ../secrets/wp_admin.txt
  my_wp_admin_passwd:
    file: ../secrets/wp_admin_password.txt
  my_wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  my_wp_user:
    file: ../secrets/wp_user.txt
  my_wp_passwd:
    file: ../secrets/wp_password.txt
  my_wp_email:
    file: ../secrets/wp_email.txt

