version: "3"

services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      MYSQL_ADMIN: ${MYSQL_ADMIN}
      MYSQL_ADMIN_PASSWD: ${MYSQL_ADMIN_PASSWD}
    volumes:
      # - "/home/barb/data:/var/lib/mysql"
      - "WP_db:/var/lib/mysql"
    networks:
      - default

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWD: ${MYSQL_PASSWD}
      HOST_DB: ${HOST_DB}
    volumes:
      # - "/home/barb/data:/var/www/html"
      - "WP_files:/var/www/html"
    networks:
      - default

  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      # - "/home/barb/data:/var/www/html"
      - "WP_files:/var/www/html"
    networks:
      - default

volumes:
  WP_db:
  WP_files:

networks:
  default:
    driver: bridge
