version: "3"

services:

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - "WP_files:/data"

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"

  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress


volumes:
  WP_files:
  DB:
