
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    expose:
     - "3306"
    env_file: .env
    secrets:
      - my_db_user
      - my_db_passwd
      - my_db_root_passwd
    volumes:
      - "DB:/var/lib/mysql"
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    depends_on:
      - mariadb
    secrets:
      - my_db_user
      - my_db_passwd
      - my_wp_admin
      - my_wp_admin_passwd
      - my_wp_user
      - my_wp_passwd
    env_file: .env
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - inception

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file: .env
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - inception

volumes:
  WP_files:
    driver: local
    driver_opts:
      type : none
      o: bind
      device: "/home/bsuc/data/wp_files"
  DB:
    driver: local
    driver_opts:
      type : none
      o: bind
      device: "/home/bsuc/data/db"

networks:
  inception:
    driver: bridge

secrets:
  my_db_user:
    file: ../secrets/db_user.txt
  my_db_passwd:
    file: ../secrets/db_password.txt
  my_db_root_passwd:
    file: ../secrets/db_root_password.txt
  my_wp_admin:
    file: ../secrets/wp_admin.txt
  my_wp_admin_passwd:
    file: ../secrets/wp_admin_password.txt
  my_wp_user:
    file: ../secrets/wp_user.txt
  my_wp_passwd:
    file: ../secrets/wp_password.txt

