version: "3"

services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 1234
    volumes:
      - "DB:/var/lib/mysql"
    networks:
      - webnet

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - webnet

  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "WP_files:/var/www/html"
    networks:
      - webnet

volumes:
  WP_files:
  DB:

networks:
  webnet:
    driver: bridge
