# version: '3'
# services:
#   your_service_name:
#     image: your_image_name
#     restart: always
#     ports:
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - ./certificates/certificate.crt:/etc/ssl/certs/certificate.crt
#       - ./certificates/private.key:/etc/ssl/private/private.key