
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      # - "/home/barb/data:/var/lib/mysql"
      - "WP_db:/var/lib/mysql"
    networks:
      - test

  wordpress:
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      # - "/home/barb/data:/var/www/html"
      - "WP_files:/var/www/html"
    networks:
      - test

  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file: .env
    volumes:
      # - "/home/barb/data:/var/www/html"
      - "WP_files:/var/www/html"
    networks:
      - test

volumes:
  WP_db:
  WP_files:

# networks:
#   default:
#     driver: bridge

networks:
  test:
    name: test
    driver: bridge
