{
 "title": "All containers stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id!=\"/\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total containers CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"/\"}[$__rate_interval])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id!=\"/\"}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total RAM usage over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"/\"}[$__rate_interval])) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Current RAM",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id!=\"/\"})",
     "legendFormat": "{{name}}"
    },
    { "expr": "machine_memory_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Current RAM usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id!=\"/\"})",
     "legendFormat": "Current RAM usage"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 25, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "Total RAM" }
   ]
  },
  {
   "title": "RAM over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id!=\"/\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total RAM usage over time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id!=\"/\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{id!=\"/\"})",
     "legendFormat": "Total bytes received"
    }
   ]
  },
  {
   "title": "Received vs. Transmitted",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{id!=\"/\"})",
     "legendFormat": "Received bytes"
    },
    {
     "expr": "sum(container_network_transmit_bytes_total{id!=\"/\"})",
     "legendFormat": "Transmitted bytes"
    }
   ]
  },
  {
   "title": "Total bytes transmitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{id!=\"/\"})",
     "legendFormat": "Total bytes transmitted"
    }
   ]
  },
  {
   "title": "Network received bytes by container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{id!=\"/\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network transmitted bytes by container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{id!=\"/\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total disk usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id!=\"/\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "container_fs_limit_bytes{name=\"nginx\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Current disk usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id!=\"/\"})",
     "legendFormat": "Current disk usage"
    }
   ]
  },
  {
   "title": "Total disk available",
   "type": "stat",
   "gridPos": { "h": 19, "w": 3, "x": 21, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_limit_bytes{name=\"nginx\"}",
     "legendFormat": "Total disk"
    }
   ]
  },
  {
   "title": "Disk usage overtime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{id!=\"/\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}