{
 "title": "Nginx main server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "Requests/s"
    }
   ]
  },
  {
   "title": "Nginx connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_connections_reading", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_connections_waiting", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_connections_writing", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Nginx stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_connections_accepted", "legendFormat": "{{__name__}}" },
    { "expr": "nginx_connections_active", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}