{
 "title": "grafana container stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Start date and time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_start_time_seconds{name=\"grafana\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Time since start",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"grafana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU usage %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 1, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"grafana\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"grafana\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    }
   ]
  },
  {
   "title": "Current RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"grafana\"}",
     "legendFormat": "memory usage"
    },
    { "expr": "machine_memory_bytes", "legendFormat": "total memory available" }
   ]
  },
  {
   "title": "Memory usage (RAM)",
   "type": "timeseries",
   "description": "Current memory usage, including all memory regardless of when it was accessed. / Current working set",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"grafana\"}",
     "legendFormat": "Total memory used, including cache and buffers"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"grafana\"}",
     "legendFormat": "Memory actively in use, without cache and buffers"
    }
   ]
  },
  {
   "title": "Total RAM available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_memory_bytes", "legendFormat": "Total ram available" }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"grafana\"}",
     "legendFormat": "Total bytes received"
    }
   ]
  },
  {
   "title": "Transmitted vs. Received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"grafana\"}",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"grafana\"}",
     "legendFormat": "Bytes transmited"
    }
   ]
  },
  {
   "title": "Network bytes transmitted per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"grafana\"}[$__rate_interval])",
     "legendFormat": "Bytes transmitted"
    }
   ]
  },
  {
   "title": "Network Bytes Received Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"grafana\"}[$__rate_interval])",
     "legendFormat": "Received bytes/second"
    }
   ]
  },
  {
   "title": "Total bytes transmitted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"grafana\"}",
     "legendFormat": "Total bytes transmitted"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_fs_usage_bytes{name=\"grafana\"} / container_fs_limit_bytes{name=\"grafana\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"grafana\"}",
     "legendFormat": "Filesystem usage"
    }
   ]
  },
  {
   "title": "Maximun disk storage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_fs_limit_bytes{name=\"grafana\"}",
     "legendFormat": "Maximum disk storage"
    }
   ]
  }
 ]
}