{
 "title": "prometheus container stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Start date and time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_start_time_seconds{name=\"prometheus\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Time since start",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU system/user",
   "type": "piechart",
   "description": "CPU time spent on system operations versus user-level processes within the container.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{name=\"prometheus\"}",
     "legendFormat": "System CPU time"
    },
    {
     "expr": "container_cpu_user_seconds_total{name=\"prometheus\"}",
     "legendFormat": "User CPU time"
    }
   ]
  },
  {
   "title": "CPU sytem/user/total",
   "type": "timeseries",
   "description": "CPU usage, showing the overall CPU consumption alongside the breakdown between system and user-level processes.",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"prometheus\"}",
     "legendFormat": "Total CPU time"
    },
    {
     "expr": "container_cpu_system_seconds_total{name=\"prometheus\"}",
     "legendFormat": "System CPU time"
    },
    {
     "expr": "container_cpu_user_seconds_total{name=\"prometheus\"}",
     "legendFormat": "User CPU time"
    }
   ]
  },
  {
   "title": "Received network traffic vs errors received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Total bytes received"
    },
    {
     "expr": "container_network_receive_errors_total{name=\"prometheus\"}",
     "legendFormat": "Total errors received"
    }
   ]
  },
  {
   "title": "Network Traffic and Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Total bytes received"
    },
    {
     "expr": "container_network_receive_errors_total{name=\"prometheus\"}",
     "legendFormat": "Total errors received"
    }
   ]
  },
  {
   "title": "Network Transmission Breakdown",
   "type": "piechart",
   "description": "The proportion of total network bytes transmitted versus network transmission errors.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Total Bytes transmitted"
    },
    {
     "expr": "container_network_transmit_errors_total{name=\"prometheus\"}",
     "legendFormat": "Total Transmit Errors"
    }
   ]
  },
  {
   "title": "Network Transmission and Errors Over Time",
   "type": "timeseries",
   "description": "shows the trends in network transmission bytes and transmission errors, tracking changes in outgoing network traffic and error rates over time.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Total bytes transmitted"
    },
    {
     "expr": "container_network_transmit_errors_total{name=\"prometheus\"}",
     "legendFormat": "Total errors transmitted"
    }
   ]
  },
  {
   "title": "Network Traffic Breakdown: Transmitted vs. Received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Bytes Transmitted"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"prometheus\"}",
     "legendFormat": "Bytes Received"
    }
   ]
  },
  {
   "title": "Memory usage (RAM)",
   "type": "timeseries",
   "description": "Current memory usage, including all memory regardless of when it was accessed. / Current working set",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"prometheus\"}",
     "legendFormat": "Total memory used, including cache and buffers"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"prometheus\"}",
     "legendFormat": "Memory actively in use, without cache and buffers"
    }
   ]
  },
  {
   "title": "Filesystem Usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"prometheus\"}",
     "legendFormat": "Filesystem usage"
    }
   ]
  }
 ]
}