{
 "title": "Nginx container stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_start_time_seconds{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU system/user",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_cpu_user_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "CPU sytem/user/total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_cpu_system_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_cpu_user_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_network_receive_errors_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_network_receive_errors_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_packets_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_network_receive_packets_dropped_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "expr": "container_network_receive_packets_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_network_receive_packets_dropped_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_errors_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_errors_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_packets_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_packets_dropped_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
   "targets": [
    {
     "expr": "container_network_transmit_packets_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_packets_dropped_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"nginx\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "File Sytem stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "container_fs_reads_total{device=\"/dev/sda3\", name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_fs_writes_total{name=\"nginx\", device=\"/dev/sda3\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    },
    {
     "expr": "container_fs_io_time_weighted_seconds_total{name=\"nginx\"}",
     "legendFormat": "{{name}} : {{__name__}}"
    }
   ]
  }
 ]
}